name: 'E-Extend'
 
on:
  push:
    branches: [ "main" ]
  schedule:
    # UTC time (国内 UTC+8)
    - cron: '0 2 1 * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-12
    
    steps:
        - name: 'Checkout codes'
          uses: actions/checkout@v2

        - name: 'Environment Settings'
          run: |
            pip3 install -r ./requirements.txt
            brew update
            brew upgrade --cask google-chrome            

        - name: 'Renew'
          env:
            EU_USER_ID: ${{ secrets.EU_USER_ID }}
            EU_PASS_WD: ${{ secrets.EU_PASS_WD }}
            CAPTCHA_USER_ID: ${{ secrets.CAPTCHA_USER_ID }}
            CAPTCHA_APIKEY: ${{ secrets.CAPTCHA_APIKEY }}
            MAILPARSER: ${{ secrets.MAILPARSER }}
            BARK_KEY: ${{ secrets.BARK_KEY }}
            TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
            TG_USER_ID: ${{ secrets.TG_USER_ID }}
            
          run: |
            python3 ./main.py
